### ISSUE TITLE
init: Is init a POSIX utility?

### ISSUE THREAD

**Issue by mssun** [mesalock-linux/mesabox#19]
I didn't find init in the POSIX standard (http://pubs.opengroup.org/onlinepubs/9699919799/idx/utilities.html).

How about treat init itself as a "type"/"feature" (similar with "POSIX", "Netowrking", etc)?.

Also, I am trying to compile mesabox in OS X (`x86_64-apple-darwin`). `init` (in "posix" feature) and `getty` (in "loginutils" feature) are not compatible with OSX (which are not designed and supposed to work in OSX). Therefore, for people who want to use it in OSX can simply exclude "init" and "loginutils" feature.

Anyway, I don't think supporting OSX is the first priority.

**Comment by Arcterus** [comment]
It's probably not, but I wasn't sure where to put it when I first added it.  Separating it out into its own feature (along with other system start-up related utilities) makes sense to me.

**Comment by Arcterus** [comment]
This should be resolved by 8314b9cdf8dd8ca67d3841c3d1e450f75ded2d95.
