### ISSUE TITLE
Remove build targets

### ISSUE THREAD

**Issue by Arcterus** [mesalock-linux/mesabox#38]
We can probably remove the `1.26.2` targets on ARM, as if they work on x86_64 they'll likely work on ARM (we don't do much architecture-specific stuff at the moment).  We can also probably combine the formatting target with the normal `stable` Linux target.

**Comment by mssun** [comment]
Fixed in the commit: https://github.com/mesalock-linux/mesabox/commit/679459afd359b779b43649e0e2f4525735d6cf4b
